In [1]:
import numpy as np 
import time

from reachy import Reachy, parts

import sys
sys.path.append('../')
from behavior.embeddings import Embeddings

import h5py as h5

In [15]:
emb_lis =np.load('/home/pi/dev/reachy-flyers-2/embeddings_data/emb_list.npy')

In [13]:
emb_lis =np.load('/home/pi/dev/reachy-flyers-2/embeddings_data/names_list.npy')

FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/dev/reachy-flyers-2/embeddings_data/names_list.npy'

array([[2.98823524, 2.98823524, 2.75294113, 2.75294113, 2.91764712,
        3.10588241, 2.58823538, 3.20000005, 3.20000005, 3.17647076,
        3.5058825 , 2.98823524, 3.05882359, 3.05882359, 2.84705877,
        3.08235312, 2.68235302, 2.84705877, 2.84705877, 2.82352948,
        2.32941175, 2.37647057, 2.25882363, 2.25882363, 2.28235292],
       [1.15294123, 0.89411765, 1.27058828, 1.27058828, 1.10588241,
        0.89411765, 1.12941182, 1.15294123, 1.15294123, 1.082353  ,
        1.22352946, 0.94117647, 0.94117647, 0.94117647, 1.38823533,
        1.05882359, 1.15294123, 0.84705883, 0.84705883, 1.24705887,
        1.27058828, 1.41176474, 1.3176471 , 1.3176471 , 1.3176471 ],
       [1.95294118, 2.07058835, 1.90588236, 1.90588236, 1.78823531,
        1.67058825, 1.57647061, 1.97647059, 1.97647059, 1.85882354,
        2.09411764, 1.62352943, 1.78823531, 1.78823531, 1.64705884,
        1.7647059 , 1.78823531, 1.97647059, 1.97647059, 1.81176472,
        1.52941179, 1.7647059 , 1.45882356, 1.

In [14]:
emb_lis.shape

(640,)

In [9]:
emb_lis[:,-1]

array([3.20000005, 1.15294123, 1.92941177, 0.        , 3.01176476,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.28235295, 0.        , 0.        , 0.51764709,
       1.34117651, 1.17647064, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.92941177,
       0.        , 0.        , 0.14117648, 0.        , 0.        ,
       0.        , 2.98823524, 2.18823528, 0.        , 0.        ,
       0.89411765, 0.        , 0.82352942, 0.02352941, 0.49411765,
       0.        , 0.        , 2.91764712, 0.        , 0.        ,
       1.22352946, 1.20000005, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.3176471 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.51764709, 0.        , 0.        , 0.        , 0.09411765,
       2.30588245, 0.        , 0.23529412, 1.15294123, 1.92941

In [10]:
emb_lis[:,-2]

array([3.01176476, 1.27058828, 1.83529413, 0.        , 3.17647076,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.61176473, 0.1882353 , 0.        , 0.14117648,
       1.15294123, 1.10588241, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.81176472,
       0.14117648, 0.        , 0.        , 0.        , 0.        ,
       0.        , 3.01176476, 2.21176481, 0.        , 0.        ,
       0.5411765 , 0.02352941, 0.89411765, 0.        , 0.42352942,
       0.        , 0.        , 2.68235302, 0.        , 0.        ,
       0.96470588, 1.20000005, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.52941179,
       0.        , 0.        , 0.16470589, 0.        , 0.        ,
       0.49411765, 0.        , 0.        , 0.        , 0.        ,
       2.09411764, 0.        , 0.        , 0.65882355, 1.71764